import "./globals.css";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import Navbar from "@/ui/navbar";
import Footer from "@/ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Landing Page Example App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className={styles.header}>
					<Navbar></Navbar>
				</header>
				<main>{children}</main>
				<Footer></Footer>
			</body>
		</html>
	);
}
