import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/ui/navbar";
import Footer from "@/ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Landing Page Example App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="flex content-center bg-white min-h-[100px] px-10 border-b-2 border-solid border-green mb-10">
					<Navbar></Navbar>
				</header>
				<main>{children}</main>
				<Footer></Footer>
			</body>
		</html>
	);
}
